### ISSUE TITLE
filter2(하루 당 과목 간 공강 시간 필터) 기준

### ISSUE THREAD

**Issue by binary-0** [monocerotis20/skku-timeTable#13]
저희가 초기 디자인에서도 그렇고 현재 result.html에도 올라와 있듯이 filter2는 '과목 간 공강 시간'이었는데, 지금 구현되어 있는 것들을 보니 시간표 시스템이 시간보다는 교시를 베이스로 작동되는 것 같습니다.
물론 이 필터에서는 시간 기준으로도 계산할 수도 있지만 교시를 기준으로 '과목 간 최대 공강 교시'와 같은 방식이 더 직관적일 것 같은데 어떻게 생각하시나요?

**Comment by monocerotis20** [comment]
네 좋은 생각입니다!

**Comment by s0y0ung** [comment]
괜찮은거 같아요!
