### ISSUE TITLE
feat: 과목 중복 허용 여부

### ISSUE THREAD

**Issue by s0y0ung** [monocerotis20/skku-timeTable#16]
같은 과목에 대해서는 시간표 생성이 불가능하도록 하려고 하는데 어떻게 생각하시나요?
ex) group1과 group2에 서로 다른 자료구조개론이 있는 경우

**Comment by monocerotis20** [comment]
혹시 현재 기능으로는 말씀하신 상황이 오류가 나나요? 기본적으로는 사용자가 같은 과목을 다른 그룹에 넣는 일은 없을거라 생각합니다. 그럼에도 말씀하신 상황이 발생한다면

1) 오류창을 띄운다
2) 시간표를 만들지 않는다

의 해결이 있을거 같습니다!

**Comment by binary-0** [comment]
현재 기능으로는 같은 자료구조개론이라도 학수번호가 다르면 하나의 시간표에 두 개 이상 들어가는 게 허용되고 있습니다. 보통 수강신청할 때 같은 과목을 두 개 신청할 수는 없게 하니 이 케이스를 배제하는 것도 좋아 보여요
제 생각으로는 이 케이스가 나오면 시간표를 만들지 않고 스킵하는 해결책이 좋을 것 같습니다

**Comment by s0y0ung** [comment]
오류가 나는건 아닌데, 원래 저희 학교에서 같은 과목에 대해서는 중복 수강이 불가능하도록 되어있어서요. 
그래서 2의 방안을 선택하려고 하는데 어떠신가요?

**Comment by monocerotis20** [comment]
네 알겠습니다!
